// Courtesy of https://twitter.com/lrgmnn/status/813635533658144768/
export const cards = [
  { url: 'https://agoric.com', name: 'Sleve McDichael' },
  { url: 'https://agoric.com', name: 'Onson Sweemey' },
  { url: 'https://agoric.com', name: 'Darryl Archideld' },
  { url: 'https://agoric.com', name: 'Anatoli Smorin' },
  { url: 'https://agoric.com', name: 'Rey McSriff' },
  { url: 'https://agoric.com', name: 'Glenallen Mixon' },
  { url: 'https://agoric.com', name: 'Mario McRlwain' },
  { url: 'https://agoric.com', name: 'Raul Chamgerlain' },
  { url: 'https://agoric.com', name: 'Kevin Nogilny' },
  { url: 'https://agoric.com', name: 'Tony Smehrik' },
  { url: 'https://agoric.com', name: 'Bobson Dugnutt' },
  { url: 'https://agoric.com', name: 'Willie Dustice' },
  { url: 'https://agoric.com', name: 'Jeromy Gride' },
  { url: 'https://agoric.com', name: 'Scott Dourque' },
  { url: 'https://agoric.com', name: 'Shown Furcotte' },
  { url: 'https://agoric.com', name: 'Dean Wesrey' },
  { url: 'https://agoric.com', name: 'Mike Truk' },
  { url: 'https://agoric.com', name: 'Dwigt Rortugal' },
  { url: 'https://agoric.com', name: 'Tim Sandaele' },
  { url: 'https://agoric.com', name: 'Karl Dandleton' },
  { url: 'https://agoric.com', name: 'Mike Sernandez' },
  { url: 'https://agoric.com', name: 'Todd Bonzalez' },
];
